# Generated by Django 5.1.7 on 2025-04-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('estado', models.CharField(max_length=20)),
                ('progreso', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
